// export const CREATE_PLAYER = 'CREATE_PLAYER';
export const LOAD_PLAYER_SUCCESS = 'LOAD_ PLAYER_SUCCESS';
export const LOAD_IPLTEAMS_SUCCESS = 'LOAD_IPLTEAMS_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
